/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Process
 #	author : miyako
 #	2016/07/20
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONWIN
#include <TlHelp32.h>
#endif

// --- Process
void PROCESS_GET_ARGUMENTS(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_SET_VARIABLE(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_GET_VARIABLE(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_GET_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void PROCESS_Get_id(sLONG_PTR *pResult, PackagePtr pParams);
