/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Process
 #	author : miyako
 #	2016/07/20
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

#include <mutex>

// Guards access to the process-wide OS environment block (setenv/getenv on
// mac, SetEnvironmentVariable/GetEnvironmentVariable on Windows). Both are
// declared threadSafe in manifest.json, but neither underlying OS call is
// safe against concurrent Set/Get from other threads without external
// synchronization -- see PROCESS_SET_VARIABLE / PROCESS_GET_VARIABLE below.
static std::mutex gEnvVarMutex;

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
	try
	{
		PA_long32 pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Process

		case 1 :
			PROCESS_GET_ARGUMENTS(pResult, pParams);
			break;

		case 2 :
			PROCESS_SET_VARIABLE(pResult, pParams);
			break;

		case 3 :
			PROCESS_GET_VARIABLE(pResult, pParams);
			break;

		case 4 :
			PROCESS_GET_LIST(pResult, pParams);
			break;
			
		case 5 :
			PROCESS_Get_id(pResult, pParams);
			break;
			
	}
}

// ------------------------------------ Process -----------------------------------


void PROCESS_GET_ARGUMENTS(sLONG_PTR *pResult, PackagePtr pParams)
{
	ARRAY_TEXT Param1;

#if VERSIONWIN
	int nArgs;
	LPWSTR *szArglist = CommandLineToArgvW(GetCommandLineW(), &nArgs);
	
	if(szArglist)
	{
		Param1.setSize(1);
		
		for(int i = 0; i < nArgs; ++i)
		{
			Param1.appendUTF16String((const PA_Unichar *)szArglist[i]);
		}
		LocalFree(szArglist);
	}
#else
	@autoreleasepool
	{
		NSArray *arguments = [[NSProcessInfo processInfo]arguments];
		
		Param1.setSize(1);
		
		for(unsigned int i = 0;i < [arguments count];++i)
		{
			Param1.appendUTF16String([arguments objectAtIndex:i]);
		}
	}
#endif

	Param1.toParamAtIndex(pParams, 1);
}

void PROCESS_SET_VARIABLE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT Param2;

	Param1.fromParamAtIndex(pParams, 1);
	Param2.fromParamAtIndex(pParams, 2);

	std::lock_guard<std::mutex> lock(gEnvVarMutex);

#if VERSIONMAC
	CUTF8String name, value;
	Param1.copyUTF8String(&name);
	Param2.copyUTF8String(&value);
	
	if(name.length())
	{
		setenv((const char *)name.c_str(), (const char *)value.c_str(), 1);
	}
#else
	CUTF16String name, value;
	Param1.copyUTF16String(&name);
	Param2.copyUTF16String(&value);
	
	if(name.length())
	{
		SetEnvironmentVariable((LPCTSTR)name.c_str(), (LPCTSTR)value.c_str());
	}
#endif
}

void PROCESS_GET_VARIABLE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT Param2;

	Param1.fromParamAtIndex(pParams, 1);

	std::lock_guard<std::mutex> lock(gEnvVarMutex);

#if VERSIONMAC
	CUTF8String name, value;
	Param1.copyUTF8String(&name);
	
	if(name.length())
	{
		const char *env = getenv((const char *)name.c_str());
		if(env)
		{
			value = CUTF8String((const uint8_t *)env);
			Param2.setUTF8String(&value);
		}
	}
#else
	DWORD size = 0;
	CUTF16String name, value;
	Param1.copyUTF16String(&name);
	
	if(name.length())
	{
		if((size = GetEnvironmentVariable((LPCTSTR)name.c_str(), NULL, 0)) != 0)
		{
			std::vector<wchar_t> buf(size);
			GetEnvironmentVariable((LPCTSTR)name.c_str(), (LPTSTR)&buf[0], size);
			value = CUTF16String((const PA_Unichar *)&buf[0]);
			Param2.setUTF16String(&value);
		}
	}
#endif

	Param2.toParamAtIndex(pParams, 2);
}

void PROCESS_Get_id(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT returnValue;

	// This is the only command in this file with a declared return value
	// (manifest.json: "PROCESS Get id:L"). PluginMain's outer try/catch has
	// no return-value context to fall back on, so a local try/catch here
	// guarantees setReturn() always runs -- without it, an exception on this
	// path would leave the host waiting indefinitely for a return that never
	// comes, rather than just crashing or no-op'ing.
	try
	{
#if VERSIONMAC
		ProcessSerialNumber psn;
		pid_t pid = 0;
		
		if(GetCurrentProcess(&psn) == noErr)
			GetProcessPID(&psn, &pid);
		
		returnValue.setIntValue(pid);
#else
		returnValue.setIntValue((unsigned int)GetCurrentProcessId());
#endif
	}
	catch(...)
	{
		returnValue.setIntValue(-1);
	}
	
	returnValue.setReturn(pResult);
}

void PROCESS_GET_LIST(sLONG_PTR *pResult, PackagePtr pParams)
{
	ARRAY_TEXT Param1;
	ARRAY_TEXT Param2;
	ARRAY_LONGINT Param3;
	
	Param1.setSize(1);
	Param2.setSize(1);
	Param3.setSize(1);
	
#if VERSIONWIN
	HANDLE hProcessSnap = INVALID_HANDLE_VALUE;
	PROCESSENTRY32 pe32;
	
	HANDLE hModuleSnap = INVALID_HANDLE_VALUE;
	MODULEENTRY32 me32;
	
	hProcessSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
	
	if(hProcessSnap != INVALID_HANDLE_VALUE)
	{
		pe32.dwSize = sizeof(PROCESSENTRY32);
		
		if(Process32First(hProcessSnap, &pe32))
		{
			do
			{
				hModuleSnap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, pe32.th32ProcessID);
				
				if(hModuleSnap != INVALID_HANDLE_VALUE)
				{
					me32.dwSize = sizeof(MODULEENTRY32);
					
					// Module32First always returns the process's own executable
					// module first (documented Windows behavior), so there's no
					// need to walk the rest of the module list comparing names.
					if(Module32First(hModuleSnap, &me32))
					{
						CUTF16String p1 = (const PA_Unichar*)me32.szModule;
						Param1.appendUTF16String(&p1);
						CUTF16String p2 = (const PA_Unichar*)me32.szExePath;
						Param2.appendUTF16String(&p2);
						Param3.appendIntValue(me32.th32ProcessID);
					}
					
					// Always close, regardless of whether Module32First
					// succeeded -- previously this was only reached on the
					// success path, leaking a handle per process where it
					// failed (e.g. protected/system processes).
					CloseHandle(hModuleSnap);
				}
				
			}while(Process32Next(hProcessSnap, &pe32));
			CloseHandle(hProcessSnap);
		}
	}
#else
	@autoreleasepool
	{
		NSWorkspace *sharedWorkspace = [NSWorkspace sharedWorkspace];
		NSArray *launchedApplications = [sharedWorkspace launchedApplications];
		
		unsigned int i;
		
		for(i = 0; i < [launchedApplications count]; i++)
		{
			NSString *NSApplicationName = (NSString *)[[launchedApplications objectAtIndex:i] valueForKey:@"NSApplicationName"];
			Param1.appendUTF16String(NSApplicationName);
			
			NSString *NSApplicationPath = (NSString *)[[launchedApplications objectAtIndex:i] valueForKey:@"NSApplicationPath"];
			NSURL *url = [[NSURL alloc]initFileURLWithPath:NSApplicationPath];
			
			if(url)
			{
				NSString *filePath = (NSString *)CFURLCopyFileSystemPath((CFURLRef)url, kCFURLHFSPathStyle);
				Param2.appendUTF16String(filePath);
				[filePath release];
				[url release];
			}else{
				Param2.appendUTF16String(@"");
			}
			
			NSNumber *NSApplicationProcessIdentifier = (NSNumber *)[[launchedApplications objectAtIndex:i] valueForKey:@"NSApplicationProcessIdentifier"];
			Param3.appendIntValue([NSApplicationProcessIdentifier intValue]);
		}
	}
#endif
	
	Param1.toParamAtIndex(pParams, 1);
	Param2.toParamAtIndex(pParams, 2);
	Param3.toParamAtIndex(pParams, 3);
	
}
